import type { RecipeDefinition } from "./types";

export const recipeCatalog: RecipeDefinition[] = [
  { id: "avena", name: "Avena con banana", minutes: 8, difficulty: "Fácil", estimatedCost: 900, ingredients: ["avena", "leche", "banana"], appliances: ["microondas"], tags: ["rapido", "economico", "principiante"], mealTypes: ["breakfast", "snack"] },
  { id: "tostadas-queso", name: "Tostadas con queso y fruta", minutes: 7, difficulty: "Fácil", estimatedCost: 1200, ingredients: ["pan integral", "queso", "banana"], appliances: [], tags: ["rapido", "principiante"], mealTypes: ["breakfast", "snack"] },
  { id: "yogur-granola", name: "Yogur con granola", minutes: 5, difficulty: "Fácil", estimatedCost: 1100, ingredients: ["yogur", "granola", "banana"], appliances: [], tags: ["rapido", "principiante"], mealTypes: ["breakfast", "snack"] },
  { id: "huevos-tostadas", name: "Huevos revueltos con tostadas", minutes: 12, difficulty: "Fácil", estimatedCost: 1300, ingredients: ["huevos", "pan integral", "queso"], appliances: ["anafe"], tags: ["rapido", "principiante"], mealTypes: ["breakfast", "snack"] },
  { id: "licuado-banana", name: "Licuado de banana y avena", minutes: 6, difficulty: "Fácil", estimatedCost: 950, ingredients: ["banana", "leche", "avena"], appliances: ["licuadora"], tags: ["rapido", "economico"], mealTypes: ["breakfast", "snack"] },
  { id: "tarta-espinaca", name: "Tarta de espinaca", minutes: 35, difficulty: "Fácil", estimatedCost: 2400, ingredients: ["espinaca", "huevos", "harina integral", "queso"], appliances: ["horno"], tags: ["economico", "verduras", "principiante"], mealTypes: ["lunch", "dinner"] },
  { id: "sopa-verduras", name: "Sopa de verduras", minutes: 30, difficulty: "Fácil", estimatedCost: 1600, ingredients: ["cebolla", "zanahoria", "zapallo"], appliances: ["anafe"], tags: ["economico", "verduras", "una-olla"], mealTypes: ["lunch", "dinner"] },
  { id: "ensalada-lentejas", name: "Ensalada de lentejas", minutes: 20, difficulty: "Fácil", estimatedCost: 1800, ingredients: ["lentejas", "tomates", "cebolla"], appliances: [], tags: ["rapido", "economico", "principiante"], mealTypes: ["lunch", "dinner"] },
  { id: "tortilla-papas", name: "Tortilla de papas", minutes: 35, difficulty: "Fácil", estimatedCost: 2100, ingredients: ["huevos", "papas", "cebolla"], appliances: ["anafe"], tags: ["economico", "principiante"], mealTypes: ["lunch", "dinner"] },
  { id: "arroz-pollo", name: "Arroz con pollo", minutes: 35, difficulty: "Fácil", estimatedCost: 2800, ingredients: ["arroz", "pollo", "cebolla", "zanahoria"], appliances: ["anafe"], tags: ["una-olla", "principiante"], mealTypes: ["lunch", "dinner"] },
  { id: "pasta-pomodoro", name: "Pasta al pomodoro", minutes: 25, difficulty: "Fácil", estimatedCost: 1900, ingredients: ["pasta seca", "tomates", "cebolla"], appliances: ["anafe"], tags: ["rapido", "economico"], mealTypes: ["lunch", "dinner"] },
  { id: "wrap-pollo", name: "Wrap de pollo", minutes: 20, difficulty: "Fácil", estimatedCost: 2600, ingredients: ["tortillas", "pollo", "tomates", "lechuga"], appliances: ["anafe"], tags: ["rapido", "principiante"], mealTypes: ["lunch", "dinner"] },
  { id: "salteado-verduras", name: "Salteado de verduras", minutes: 25, difficulty: "Fácil", estimatedCost: 1700, ingredients: ["cebolla", "zanahoria", "zapallito", "arroz"], appliances: ["anafe"], tags: ["rapido", "economico", "verduras"], mealTypes: ["lunch", "dinner"] },
  { id: "guiso-lentejas", name: "Guiso de lentejas", minutes: 45, difficulty: "Media", estimatedCost: 2300, ingredients: ["lentejas", "papas", "cebolla", "zanahoria"], appliances: ["anafe"], tags: ["economico", "una-olla"], mealTypes: ["lunch", "dinner"] },
  { id: "pescado-horno", name: "Pescado al horno", minutes: 35, difficulty: "Media", estimatedCost: 3400, ingredients: ["pescado", "papas", "limon"], appliances: ["horno"], tags: ["horno"], mealTypes: ["lunch", "dinner"] },
  { id: "sandwich", name: "Sándwich completo", minutes: 15, difficulty: "Fácil", estimatedCost: 2200, ingredients: ["pan integral", "queso", "tomates", "lechuga"], appliances: [], tags: ["rapido", "principiante"], mealTypes: ["lunch", "dinner"] },
  { id: "crema-zapallo", name: "Crema de zapallo", minutes: 30, difficulty: "Fácil", estimatedCost: 1700, ingredients: ["zapallo", "cebolla", "leche"], appliances: ["anafe"], tags: ["economico", "verduras", "una-olla"], mealTypes: ["lunch", "dinner"] },
  { id: "ensalada-mixta", name: "Ensalada mixta", minutes: 15, difficulty: "Fácil", estimatedCost: 1500, ingredients: ["tomates", "lechuga", "cebolla", "huevos"], appliances: [], tags: ["rapido", "economico", "verduras"], mealTypes: ["lunch", "dinner"] },
  { id: "fideos-verduras", name: "Fideos con verduras", minutes: 25, difficulty: "Fácil", estimatedCost: 1900, ingredients: ["pasta seca", "cebolla", "zanahoria", "zapallito"], appliances: ["anafe"], tags: ["rapido", "economico"], mealTypes: ["lunch", "dinner"] },
  { id: "omelette", name: "Omelette de vegetales", minutes: 15, difficulty: "Fácil", estimatedCost: 1700, ingredients: ["huevos", "espinaca", "tomates"], appliances: ["anafe"], tags: ["rapido", "principiante"], mealTypes: ["breakfast", "lunch", "dinner"] },
  { id: "bowl-arroz", name: "Bowl de arroz y vegetales", minutes: 25, difficulty: "Fácil", estimatedCost: 1800, ingredients: ["arroz", "zanahoria", "tomates", "huevos"], appliances: ["anafe"], tags: ["rapido", "economico"], mealTypes: ["lunch", "dinner"] },
  { id: "papas-rellenas", name: "Papas rellenas", minutes: 40, difficulty: "Media", estimatedCost: 2300, ingredients: ["papas", "queso", "cebolla", "espinaca"], appliances: ["horno"], tags: ["horno", "economico"], mealTypes: ["lunch", "dinner"] },
  { id: "quinoa", name: "Bowl de quinoa", minutes: 30, difficulty: "Media", estimatedCost: 2800, ingredients: ["quinoa", "tomates", "zanahoria", "huevos"], appliances: ["anafe"], tags: ["verduras"], mealTypes: ["lunch", "dinner"] },
];

export const ingredientPrices: Record<string, { amount: string; price: number }> = {
  "harina integral": { amount: "1 paquete", price: 1800 },
  queso: { amount: "300 g", price: 3200 },
  zapallo: { amount: "1 kg", price: 2100 },
  lentejas: { amount: "500 g", price: 1900 },
  papas: { amount: "1 kg", price: 1800 },
  pollo: { amount: "700 g", price: 5600 },
  "pasta seca": { amount: "1 paquete", price: 1700 },
  tortillas: { amount: "1 paquete", price: 2100 },
  lechuga: { amount: "1 planta", price: 1400 },
  zapallito: { amount: "500 g", price: 1600 },
  pescado: { amount: "500 g", price: 6200 },
  limon: { amount: "2 unidades", price: 900 },
  "pan integral": { amount: "1 paquete", price: 2300 },
  quinoa: { amount: "500 g", price: 3600 },
  avena: { amount: "500 g", price: 1700 },
  leche: { amount: "1 litro", price: 1800 },
  banana: { amount: "1 kg", price: 2200 },
  yogur: { amount: "4 unidades", price: 3000 },
  granola: { amount: "400 g", price: 2800 },
};
